# model type
model: emt

# backend settings
backend: torch
onnx: null
triton_url: localhost:8001
triton_model_name: EMT_x3
triton_model_version: 1

# general settings
name: EMT_x3
model_type: IRModel
num_gpu: 1  # 0 for cpu mode
manual_seed: 42
bit: 8 # data type

# network
network_g:
  type: EMT
  dim: 60
  n_blocks: 6
  n_layers: 6
  n_GTLs: 2
  num_heads: 3
  mlp_ratio: 2
  window_list:  [ [32, 8],[8, 32] ]
  shift_list:   [ [16, 4],[4, 16] ]
  task: lsr
  upscale: 3
  num_in_ch: 3
  num_out_ch: 3

# path
path:
  pretrain_network_g: dvc_data/weights/emt/EMT_LSR_x3.pth
  strict_load_g: true
  resume_state: ~

# train mode
is_train: false

# distributed mode
dist: false
