model: real_esrgan
model_name: RealESRGAN_x4plus_anime_6B
backend: onnx
weights: dvc_data/weights/real-esrgan/RealESRGAN_x4plus_anime_6B.pth
onnx: dvc_data/onnx/real-esrgan/RealESRGAN_x4plus_anime_6B.onnx
outscale: 4.0
denoise_strength: 0.5
tile: 0
tile_pad: 10
pre_pad: 0
fp32: yes
gpu_id: 0
