model: real_esrgan
model_name: RealESRNet_x4plus
backend: triton
weights: dvc_data/weights/real-esrgan/RealESRNet_x4plus.pth
onnx: dvc_data/onnx/real-esrgan/RealESRNet_x4plus.onnx
triton_url: localhost:8001
triton_model_name: RealESRNet_x4plus
triton_model_version: 1
outscale: 4.0
denoise_strength: 0.5
tile: 0
tile_pad: 10
pre_pad: 0
fp32: yes
gpu_id: 0
