model: real_esrgan
model_name: RealESRGAN_x4plus
backend: triton
weights: dvc_data/weights/real-esrgan/Finetuned_RealESRGAN_x4plus_GameEngineData.pth
onnx: dvc_data/onnx/real-esrgan/Finetuned_RealESRGAN_x4plus_GameEngineData.onnx
triton_url: localhost:8001
triton_model_name: Finetuned_RealESRGAN_x4plus_GameEngineData
triton_model_version: 1
outscale: 4.0
denoise_strength: 0.5
tile: 0
tile_pad: 10
pre_pad: 0
fp32: yes
gpu_id: 0
